#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.dirname(__FILE__))
require 'yaml'
Dir["lib/*.rb"].each {|file| require file }


score = 0
story = YAML.load File.read("story.yaml")
story.each do |frame|
  frame = StoryFrame.new(frame)
  frame.display_text
  score += frame.ask_question_and_get_score
end

puts "Thank you for participating.  Good luck, and may the Agile be with you!"
